"""Add Chat Messages1

Revision ID: 8d96ae018cfc
Revises: d92ffaa40ee1
Create Date: 2026-07-05 23:37:36.542246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d96ae018cfc'
down_revision: Union[str, Sequence[str], None] = 'd92ffaa40ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
