"""Add schema snapshot

Revision ID: b89191620373
Revises: 8d96ae018cfc
Create Date: 2026-07-06 00:02:04.107528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b89191620373'
down_revision: Union[str, Sequence[str], None] = '8d96ae018cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semantic_prompt_cache', sa.Column('schema_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semantic_prompt_cache', 'schema_snapshot')
    # ### end Alembic commands ###
