"""Add Chat Messages

Revision ID: d92ffaa40ee1
Revises: 2aa497d652c1
Create Date: 2026-07-05 23:27:00.305263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92ffaa40ee1'
down_revision: Union[str, Sequence[str], None] = '2aa497d652c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('redis_cache_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_lookup', 'chat_messages', ['clerk_user_id', 'project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_clerk_user_id'), 'chat_messages', ['clerk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_clerk_user_id'), table_name='chat_messages')
    op.drop_index('idx_chat_messages_lookup', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
