"""Add schema snapshot

Revision ID: dc0098b9b550
Revises: b89191620373
Create Date: 2026-07-06 00:16:00.408321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'dc0098b9b550'
down_revision: Union[str, Sequence[str], None] = 'b89191620373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    op.create_table('semantic_prompt_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('raw_user_prompt', sa.Text(), nullable=False),
    sa.Column('compiled_sql_query', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('prompt_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('selected_tables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompt_embedding_hnsw', 'semantic_prompt_cache', ['prompt_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'prompt_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_semantic_prompt_cache_clerk_user_id'), 'semantic_prompt_cache', ['clerk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_semantic_prompt_cache_clerk_user_id'), table_name='semantic_prompt_cache')
    op.drop_index('idx_prompt_embedding_hnsw', table_name='semantic_prompt_cache', postgresql_using='hnsw', postgresql_ops={'prompt_embedding': 'vector_cosine_ops'})
    op.drop_table('semantic_prompt_cache')
    # ### end Alembic commands ###
